# Generated by Django 2.0.1 on 2018-05-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
